### ISSUE TITLE
Results from query cannot be stored "1.13.2"

### ISSUE THREAD

**Issue by TKwSni** [btk5h/skript-db#13]
Skript  Skript bensku-2.3.5
Spigot 1.13.2

execute "select * from table" in {sql} and store the result in {output::*}

It doesnt store the result and is always "none"

**Comment by Helomi** [comment]
try execute unsafe "......

**Comment by TKwSni** [comment]
nope, It doesnt work for me.

**Comment by TKwSni** [comment]
it started working again, so i'll close this issue.
