### ISSUE TITLE
[Help] Console spamming

### ISSUE THREAD

**Issue by antoinech2** [btk5h/skript-db#16]
Hello, I've a problem with the new version of skript-db
First of all, I want to thank you for updated skript-db!

With the new version, all of my request send this message in console:
`CONSOLE: WARN]: [Skript] A SQL query was attempted on the main thread!`
whether they are async or sync.

What does this message mean and what should I do to make it no longer appear?

Thank you in advance for your answer

**Comment by btk5h** [comment]
That message should only pop up when a sync query is attempted on the main thread. I'll get a hotfix out for this.

**Comment by antoinech2** [comment]
Thanks!
