### ISSUE TITLE
"WARN A SQL query was attempted on the main thread!"

### ISSUE THREAD

**Issue by BaseWalls** [btk5h/skript-db#21]
This is the "error" I am receiving in my console:
`WARN A SQL query was attempted on the main thread!`

when running this piece of code:
`execute "SELECT `uuid` FROM `team_users` WHERE `team_name` = 'test'" on {db} and store result in {_data::*}`

I also tried saving the result in a global variable, resulted in same warning.
The `synchronously` flag did not work either. Still gave me the warning.

Surely I don't have to create a new thread `$ thread` from **SkQuery** everytime?

Skript version: 2.2-dev36
skript-db version: 0.2.0

**Comment by btk5h** [comment]
This should have been fixed in 0.2.1, can you try that build?

**Comment by SpinKnight** [comment]
Where would I find that build

**Comment by BaseWalls** [comment]
Fixed it. Thank you. Does skript-db not support multiple queries at once?
`"SELECT * FROM table; UPDATE table SET column = column + 1"` basically
Cuz everytime I try it, it fails

**Comment by btk5h** [comment]
I have not tested this approach, but you may be able to execute multiple queries by connecting with the parameter `allowMultiQueries=true` in the connection uri.

If you have more follow-up questions/suggestions for this, please open them in another issue.
