### ISSUE TITLE
Add support for executing on main thread

### ISSUE THREAD

**Issue by ghost** [btk5h/skript-db#22]
I really need to execute on main thread so I wouldn't have any delays, I'm using in-memory local hosted database so connections do not need to be delayed for me, please add it

EDIT: It proved to be slow to do it on main thread, so I abandoned the idea.

**Comment by btk5h** [comment]
Unfortunately, performing I/O on the main thread is generally a terrible idea and I don't want users to fall into that trap.

I'd be open to allowing this, but we'd need some way to determine whether these calls are safe or have some sort of hidden feature that the user would have to opt-in to.

**Comment by Govindass** [comment]
why it's a terrible idea I wonder? I have edited the code to do it on main thread now, everything works just perfect, I can get data with zero-delay without lag
