### ISSUE TITLE
Can't be used in a function

### ISSUE THREAD

**Issue by Diamax10** [btk5h/skript-db#5]
We can't use execute effect in a Skript's return function because it sees effect like a delay

```
A return statement after a delay is useless, as the calling trigger will resume when the delay starts
```

**Comment by btk5h** [comment]
Use this addon with skript-mirror's delayed custom effects.

**Comment by abandonedaccount6235** [comment]
that's because it is a delay. If skript-db didnt act the way it does, it would lag your server every time you ran a request. skript-mirror's custom syntax are a great fix for this

**Comment by Diamax10** [comment]
Yeah, I will try that ;) thanks
