### ISSUE TITLE
Failed to load class at startup

### ISSUE THREAD

**Issue by Diamax10** [btk5h/skript-db#7]
Hello,

When I start my Spigot server it displays 
```
Failed to load class "org.slf4j.impl.StaticLoggerBinder".
Defaulting to no-operation (NOP) logger implementation
See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

And when I try to do an INSERT INTO in SQL my line isn't added in my MySQL server (only with skript code if I try my SQL command in phpmyadmin for example its works) :/ but I can read correctly !

Thanks for your help

**Comment by btk5h** [comment]
You can safely ignore this warning. As for your second issue, please open another issue with more details on the issue and how to replicate it.
